# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

init_system <- function(nQubits) {
    .Call('_quantumSystem_init_system', PACKAGE = 'quantumSystem', nQubits)
}

seq_int <- function(first, last) {
    .Call('_quantumSystem_seq_int', PACKAGE = 'quantumSystem', first, last)
}

meassurement <- function(quantumSystem) {
    .Call('_quantumSystem_meassurement', PACKAGE = 'quantumSystem', quantumSystem)
}

getStateProbability <- function(quantumSystem, index) {
    .Call('_quantumSystem_getStateProbability', PACKAGE = 'quantumSystem', quantumSystem, index)
}

applyHadamard <- function(quantumSystem) {
    invisible(.Call('_quantumSystem_applyHadamard', PACKAGE = 'quantumSystem', quantumSystem))
}

applyOracleFunction <- function(quantumSystem, target) {
    invisible(.Call('_quantumSystem_applyOracleFunction', PACKAGE = 'quantumSystem', quantumSystem, target))
}

applyDifussion <- function(quantumSystem) {
    invisible(.Call('_quantumSystem_applyDifussion', PACKAGE = 'quantumSystem', quantumSystem))
}

